### ISSUE TITLE
equals is not implemented correctly

### ISSUE THREAD

**Issue by kakai248** [Zhuinden/state-bundle#5]
We were using this package through simple-stack and found out that the equals method is implemented incorrectly.

`new StateBundle().equals(new StateBundle().putString("test", "xd"))`

Using this, equals will return `true` because since the first bundle doesn't have anything inside, it will skip the `for` and simply return true.

Thanks

**Comment by Zhuinden** [comment]
Oh wow. :disappointed: we never ran into this!

    @Test
    public void testEqualsWorksBetweenEmptyAndNonEmptyStateBundles() {
        StateBundle stateBundle = new StateBundle();
        StateBundle stateBundle1 = new StateBundle();
        stateBundle.putString("hello", "world");

        assertThat(stateBundle).isNotEqualTo(stateBundle1); // <-- works
        assertThat(stateBundle.equals(stateBundle1)).isFalse(); // <-- works
        assertThat(stateBundle1.equals(stateBundle)).isFalse(); // <-- fails!!!
    }

Fixed in 1.2.1

Also published in simple-stack 1.11.2

Thanks for the notice :cry:
