### ISSUE TITLE
equals is not correctly implemented

### ISSUE THREAD

**Issue by kakai248** [Zhuinden/state-bundle#7]
```kotlin
StateBundle().putString("1", "a") == StateBundle().putString("1", "a").putString("2", "b")
// returns true

StateBundle().putString("1", "a").putString("2", "b") == StateBundle().putString("1", "a")
// returns false
```

Which is not correct. What's lacking is that the equals doesn't check if the other contains all keys of this.

Tomorrow I can work on a PR to fix the problem if you want.

Thanks

**Comment by Zhuinden** [comment]
:roll_eyes: 

Clearly I have underestimated all the ways `equals` [can go wrong](https://github.com/Zhuinden/state-bundle/issues/5#issue-344962833) and should implement a way more elaborate unit test suite for it.

Sorry you had to debug this on your side. If you already do have an idea for a fix in mind, I am definitely accepting PRs.

**Comment by Zhuinden** [comment]
Actually I was frustrated enough that I fixed it in https://github.com/Zhuinden/state-bundle/commit/f364553c04b748eae09f30e5f0b488e85f8220a9 and am making a release and then updating simple-stack's transitive dep with it

I sincerely hope I got it right this time, because I think this `equals` method is cursed, it literally [haunts me](https://github.com/Zhuinden/state-bundle/issues/2)

**Comment by kakai248** [comment]
This created some interesting bug where it was not properly cleaning fragments on the backstack and they just stood there, initialized. At first it looked like some sort of memory leak.

Thanks for fixing it!

**Comment by Zhuinden** [comment]
Beware that that can also happen if you use `Key.toString()` as the fragment tag, but don't use `data class` (or some other form of stable `toString` that doesn't append `System.identityHashcode()` to it like an `object`'s `toString()` does).

Typically we had all arguments directly on Key constructor parameters, so these oddities of StateBundle just didn't arise on our side. :persevere:

**Comment by kakai248** [comment]
> Beware that that can also happen if you use Key.toString() as the fragment tag

We are but we're also using data class for every screen:

```kotlin
@Parcelize
data class InOutScreen(override val params: StateBundle) : Screen() {
    constructor() : this(StateBundle())

    override val fragmentClass: Class<out Fragment>
        get() = InOutFragment::class.java
}
```

The default constructor accepting a StateBundle is how we inject the deep link params into the screen. Regular usage will use the secondary constructors.

**Comment by Zhuinden** [comment]
Yep, if it's a `data class` then it should have worked. Now it really should.
